import ex1Image from "../assets/ex1_image.svg";
import ex2Image from "../assets/ex2_image.svg";

const mockMemory = [
  {
    id: 1,
    groupId: 3,
    nickname: "달봉이아들",
    title: "인천 앞바다에서 낚시",
    content: "인천 앞바다에서 즐거운 낚시 모험",
    imageUrl: ex1Image,
    tags: ["인천", "낚시"],
    location: "인천 앞바다",
    moment: "2024-02-21",
    isPublic: true,
    likeCount: 120,
    commentCount: 8,
    createdAt: "2024-02-22T07:47:49.803Z",
  },
  {
    id: 2,
    groupId: 3,
    nickname: "달봉이",
    title: "설악산 등산 여행",
    content: "설악산의 아름다움을 경험한 등산 여행",
    imageUrl: ex2Image,
    tags: ["등산", "자연"],
    location: "설악산",
    moment: "2024-02-20",
    isPublic: true,
    likeCount: 150,
    commentCount: 10,
    createdAt: "2024-02-22T08:47:49.803Z",
  },
  {
    id: 3,
    groupId: 3,
    nickname: "달봉이아들",
    title: "한강 가족 피크닉을 가족과 다녀왔는데 무지 즐거웠습니다",
    content: "가족과 함께 한강에서 즐긴 피크닉",
    imageUrl: ex1Image,
    tags: ["가족", "피크닉", "한강", "봄", "나들이", "물멍", "산책", "강아지"],
    location: "한강 공원",
    moment: "2024-02-19",
    isPublic: true,
    likeCount: 200,
    commentCount: 15,
    createdAt: "2024-02-22T09:47:49.803Z",
  },
  {
    id: 4,
    groupId: 3,
    nickname: "달봉이",
    title: "봄 꽃 축제",
    content: "제주도에서 만난 아름다운 봄 꽃 축제",
    imageUrl: ex2Image,
    tags: ["봄", "꽃놀이"],
    location: "제주도",
    moment: "2024-02-18",
    isPublic: false,
    likeCount: 180,
    commentCount: 12,
    createdAt: "2024-02-22T10:47:49.803Z",
  },
  {
    id: 5,
    groupId: 3,
    nickname: "달봉이아들",
    title: "부산 해운대 휴가",
    content: "부산 해운대에서의 여름 휴가",
    imageUrl: ex1Image,
    tags: ["바다", "휴가"],
    location: "부산 해운대",
    moment: "2024-02-17",
    isPublic: false,
    likeCount: 250,
    commentCount: 20,
    createdAt: "2024-02-22T11:47:49.803Z",
  },
  {
    id: 6,
    groupId: 3,
    nickname: "달봉이",
    title: "겨울 스키 여행",
    content: "강원도에서 즐긴 겨울 스키 여행",
    imageUrl: ex2Image,
    tags: ["겨울", "스키"],
    location: "강원도 스키장",
    moment: "2024-02-16",
    isPublic: true,
    likeCount: 90,
    commentCount: 5,
    createdAt: "2024-02-22T12:47:49.803Z",
  },
  {
    id: 7,
    groupId: 3,
    nickname: "달봉이아들",
    title: "지리산 캠핑 모험",
    content: "지리산에서 캠핑하며 모험을 즐긴 여행",
    imageUrl: ex1Image,
    tags: ["캠핑", "모험"],
    location: "지리산 캠핑장",
    moment: "2024-02-15",
    isPublic: true,
    likeCount: 130,
    commentCount: 11,
    createdAt: "2024-02-22T13:47:49.803Z",
  },
  {
    id: 8,
    groupId: 3,
    nickname: "달봉이",
    title: "제주 오름에서 일몰",
    content: "제주 오름에서 본 아름다운 일몰",
    imageUrl: ex2Image,
    tags: ["일몰", "풍경"],
    location: "제주도 오름",
    moment: "2024-02-14",
    isPublic: false,
    likeCount: 220,
    commentCount: 14,
    createdAt: "2024-02-22T14:47:49.803Z",
  },
  {
    id: 9,
    groupId: 3,
    nickname: "달봉이아들",
    title: "서울 남대문 야시장 탐방",
    content: "서울 남대문 야시장에서 다양한 음식을 탐방",
    imageUrl: ex1Image,
    tags: ["야시장", "서울"],
    location: "남대문시장",
    moment: "2024-02-13",
    isPublic: false,
    likeCount: 170,
    commentCount: 9,
    createdAt: "2024-02-22T15:47:49.803Z",
  },
  {
    id: 10,
    groupId: 3,
    nickname: "달봉이",
    title: "여의도 벚꽃 산책",
    content: "서울 여의도에서 만끽한 벚꽃 산책",
    imageUrl: ex2Image,
    tags: ["벚꽃", "산책"],
    location: "여의도",
    moment: "2024-02-12",
    isPublic: true,
    likeCount: 300,
    commentCount: 22,
    createdAt: "2024-02-22T16:47:49.803Z",
  },
];

export default mockMemory;
